import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/header/Header"
import StoreProvider from "@/app/StoreProvider"
import SideMenu from "@/components/aside/SideMenu"
import Categories from "@/components/aside/category/Categories"
import SideMenuHeader from "@/components/aside/SideMenuHeader"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'shovelog',
  description: 'Generated by timel2ss',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
    <StoreProvider>
      <body className={inter.className}>
      <Header/>
      <SideMenu>
        <SideMenuHeader/>
        <Categories/>
      </SideMenu>
      {children}
      </body>
    </StoreProvider>
    </html>
  )
}
