import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/header/Header"
import StoreProvider from "@/app/StoreProvider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'shovelog',
  description: 'Generated by timel2ss',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
    <StoreProvider>
      <body className={inter.className}>
      <Header/>
      {children}
      </body>
    </StoreProvider>
    </html>
  )
}
